### ISSUE TITLE
Issues with __pow__(), exp() and ln() in Windows 64-bit python

### ISSUE THREAD

**Issue by tingtron** [mpy-dev/micropython-decimal-number#1]
Platform: Windows 10 64-bit
Python: `Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32`

The package was installed using:
```python setup.py install```
Testing was done in the Python shell after the following preamble:
```
from mpy_decimal.mpy_decimal import *
D = DecimalNumber
D.get_scale()
16
D.set_scale(48)
```

The following issues are detected:

### 1. Power to 1e6 (1,000,000) takes too long. 
`>>> (1+1/D(int(1e6))) ** int(1e6)` # does not finish

Ctrl+C  >>>  `... KeyboardInterrupt`
```
>>> D.get_scale()
1000048
```

Even though by squaring, it should only be 20 iterations:
```
>>> D(int(1e6)).ln()/D.ln2()
DecimalNumber("19.931568569324174087221916576936341055188988358155")
```

   Note: `1e5` still works:
```
>>> (1+1/D(int(1e5))) ** int(1e5)
DecimalNumber("2.718268237174489668035064824426046447974446932678")
>>> D.get_scale()
48
```
### 2. Power does not take DecimalNumber or Float
The `__pow__()` method should check input and/or convert it to `int`.

Integer `pow` works fine:
```
>>> D.set_scale(48)
>>> D('1.001')
DecimalNumber("1.001")
>>> D('1.001') ** 1000
DecimalNumber("2.716923932235892457383088121947577188964315018837")
```
But `pow` to `DecimalNumber` throws an error:
```
>>> D('1.001') ** D(1000)
  File "...\mpy_decimal\mpy_decimal.py", line 41, in __init__
  File "...\mpy_decimal\mpy_decimal.py", line 1004, in _reduce_to_scale
  File "...mpy_decimal\mpy_decimal.py", line 867, in __lt__
RecursionError: maximum recursion depth exceeded
```
and the scale is corrupted (should stay `int`)
```
>>> D.get_scale()
DecimalNumber("1016")
```
Also an error and similar "corruption" of `scale` is with Float power:
```
>>> D('1.001') ** 1e3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\mpy_decimal\mpy_decimal.py", line 838, in __pow__
  File "...\mpy_decimal\mpy_decimal.py", line 780, in __imul__
  File "...\mpy_decimal\mpy_decimal.py", line 775, in __mul__
  File "...\mpy_decimal\mpy_decimal.py", line 41, in __init__
  File "...\mpy_decimal\mpy_decimal.py", line 1015, in _reduce_to_scale
OverflowError: (34, 'Result too large')
>>> D.get_scale()
1048.0
```

Also note: `exp()` does not declare `scale` and `extra` as `int`.

### 3. ln() is very slow for values less than 1
This takes a few seconds:
```
>>> D.set_scale(200) 
>>> D(1,50).ln()     
DecimalNumber("-115.12925464970228420089957273421821038005507443143864880166639504837863048386762401179986025447991491709838920211431243167047627325414033783331436845493908447414534244258056610642733845597115586158837478")
```
This runs forever:
```
>>> D(1,195).ln() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\mpy_decimal\mpy_decimal.py", line 229, in ln
    y1 = y0 + two * ((n - y0.exp(False)) / (n + y0.exp(False)))
  File "...\mpy_decimal\mpy_decimal.py", line 167, in exp
    r = DecimalNumber._exp_lt_1(self - m * DecimalNumber.ln2()) * (2 ** m)
  File "...\mpy_decimal\mpy_decimal.py", line 191, in _exp_lt_1
    x *= n
  File "...\mpy_decimal\mpy_decimal.py", line 781, in __imul__
    n = self.__mul__(other)
  File "...\mpy_decimal\mpy_decimal.py", line 776, in __mul__
    new_number = DecimalNumber(
  File "...\mpy_decimal\mpy_decimal.py", line 42, in __init__
    self._reduce_to_scale()
  File "...\mpy_decimal\mpy_decimal.py", line 1035, in _reduce_to_scale
    self._number = (n + x) // ds
KeyboardInterrupt
```
This is because the `y0` and `y1` estimates are way "off base" for `value < 1`. (See the solution below.)

**Comment by tingtron** [comment]
One simple solution is to limit the `extra` in `pow` and manually adjust either the limit or the `set_scale()`.
```
*** mpy_decimal0/mpy_decimal.py 2022-06-08 13:19:54.000000000 -0400
--- mpy_decimal/mpy_decimal.py  2022-09-25 23:59:37.917860200 -0400
*************** class DecimalNumber:
*** 13,14 ****
--- 13,15 ----
      DEFAULT_SCALE: int = 16
+     MAX_EXTRA_SCALE: int = 64
      DECIMAL_SEP: str = "."
*************** def __pow__(self, other: int) -> "Decima
*** 826,827 ****
--- 827,829 ----
          extra = abs(other) * (len(str(self._number)) - self._num_decimals)
+         extra = min(extra, DecimalNumber.MAX_EXTRA_SCALE)
          # extra digits for intermediate steps
```
So now it works fast and correctly:
```
>>> D.set_scale(24)
>>> (1+D(1,20)) ** int(1e20)
DecimalNumber("2.718281828459045235346696")
>>> float(str(D.e() - (1+D(1,20)) ** (10**20)))
1.3591e-20
>>>
>>> D.set_scale(44)                             
>>> (1+D(1,42)) ** (10**42)                     
DecimalNumber("2.71828182845904523536028747135266249775724573")
>>> float(str(D.e() - (1+D(1,42)) ** (10**42))) 
1.36e-42
```
For very large scale, the scale needs to be manually adjusted, but linearly, not impacting performance much:
```
>>> D.set_scale(300) 
>>> float(str(D.e() - (1+D(1,300)) ** (10**300)))
1.57993142067887e-182

>>> D.set_scale(600)
>>> float(str(D.e() - (1+D(1,300)) ** (10**300)))
1.3591409142295227e-300

>>> print((1+D(1,300)) ** (10**300))
2.718281828459045235360287471352662497757247093699959574966967627724076630353547594571382178525166427427466391932003059921817413596629043572900334295260595630738132328627943490763233829880753195251019011573834187930702154089149934884167509244761460668082264800168477411853742345442437107539077744992068192561847609083643651240847324420796055203013447626949629716895466670812266973249945005887946726927979103623059513578696555065312937867997974902429827781708769699118311634806439113631422079601404952749815723972006655947423038815495845067979675248987249671412997513055334662099925451725882013270929532
```
In this particular formula, the required scale is twice the input precision:
```
>>> D.set_scale(400) 
>>> D(1,198) > (D.e() - (1+D(1,200)) ** (10**200)) 
True
>>> D(1,296) > (D.e() - (1+D(1,300)) ** (10**300)) 
False

>>> D.set_scale(600) 
>>> D(1,296) > (D.e() - (1+D(1,300)) ** (10**300))
True

>>> D.set_scale(2000) 
>>> D(1,998) > (D.e() - (1+D(1,1000)) ** (10**1000)) 
True
>>> D(1,1196) > (D.e() - (1+D(1,1200)) ** (10**1200)) 
False

>>> D.set_scale(2400)                                 
>>> D(1,1196) > (D.e() - (1+D(1,1200)) ** (10**1200))
True
>>> D(1,1200) > (D.e() - (1+D(1,1200)) ** (10**1200)) 
False
>>> D(1,1199) > (D.e() - (1+D(1,1200)) ** (10**1200)) 
True
```

It still works with numbers much larger than 1:
```
>>> len(str(101**10000)) 
20044
>>> len(str(D(101)**10000)) 
20044
>>> 101**10000 == D(101)**10000
True
```

**Comment by tingtron** [comment]
To fix **#3 ln() being very slow for values less than 1**,
because the `y0` and `y1` estimates are way "off base" for `value < 1`,
we need to apply the formula `log(1/x) = -log(x)`

```
*************** def ln(self) -> "DecimalNumber":
*** 208,210 ****
              raise DecimalNumberExceptionMathDomainError("ln(x) exists for x > 0")
!         n = self
          scale: int = DecimalNumber.get_scale()
--- 209,211 ----
              raise DecimalNumberExceptionMathDomainError("ln(x) exists for x > 0")
!         n = 1/self if self < 1 else self
          scale: int = DecimalNumber.get_scale()
*************** def ln(self) -> "DecimalNumber":
*** 230,232 ****
          DecimalNumber.set_scale(scale)
!         return +y1

--- 231,233 ----
          DecimalNumber.set_scale(scale)
!         return -y1 if self < 1 else +y1
```
And we have very fast and accurate results:
```
>>> from mpy_decimal.mpy_decimal import *
>>> 
>>> D = DecimalNumber
>>> 
>>> D.set_scale(48)
>>> D(1,20).ln()
DecimalNumber("-46.051701859880913680359829093687284152022029772575")
>>> D(1,40).ln() 
DecimalNumber("-92.103403719761827360719658187374568304044059545151")
>>> D(1,40).ln()/D(10).ln()
DecimalNumber("-39.999999999999999999999999999999999999999999999996")
>>> 
>>> D.set_scale(200)  
>>> D(1,198).ln()/D(10).ln() 
DecimalNumber("-197.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999996")
```
